DROP TABLE TAG;

CREATE TAGDATA TABLE TAG 
(
    TAG_ID       VARCHAR(40)  PRIMARY KEY,
    TIMESTAMP    DATETIME     BASETIME,
    VALUE        DOUBLE       SUMMARIZED,
    QUALITY      INTEGER
)
METADATA
(
   EQUIPMENT     VARCHAR(16),
   TAG_NAME      VARCHAR(16)
);
